Running suite(s): Default
3
foo
1
main
here
here2
here3
1
main
here2
1
main
here2
1
main
here2
1
main
here2
1
main
here2
1
main
here2
1
main
here2
1
main
here2
1
foo
1
main
here2
73%: Checks: 30, Failures: 7, Errors: 1
public.c:53:F:Public:B_conditional:0: Assertion 'valid_program("def int main () { " "if (true) { }" " }")' failed
public.c:54:F:Public:B_whileloop:0: Assertion 'valid_program("def int main () { " "while (false) { }" " }")' failed
public.c:55:F:Public:B_add_expr:0: Assertion 'valid_program("def int main () { return " "3+7" " ; }")' failed
public.c:56:F:Public:B_add_expr_bool:0: Assertion 'valid_program("def int main () { return " "true && false" " ; }")' failed
public.c:57:F:Public:B_neg_expr:0: Assertion 'valid_program("def int main () { return " "-2" " ; }")' failed
public.c:58:F:Public:A_arrays:0: Assertion 'valid_program("int a[5]; def int main() { a[1] = 7; return a[1]; }")' failed
public.c:81:F:Public:A_newline:0: Assertion 'value == "ab\nc"' failed: value == "ab\nc", "ab\nc" == "ab
c"
private.c:5:E:Private:A_null_token_queue:0: (after this point) Received signal 11 (Segmentation fault)
